-- Views and Materialized views
USE ROLE ALL_USERS_ROLE; 
USE DATABASE DATAEXPERT_STUDENT; 
USE WAREHOUSE COMPUTE_WH;

---> Use the CREATE VIEW command to create a “truck_franchise” view of the following query:
CREATE OR REPLACE VIEW DATAEXPERT_STUDENT.HARMONIZED.TRUCK_FRANCHISE_V AS
SELECT
    t.*,
    f.first_name AS franchisee_first_name,
    f.last_name AS franchisee_last_name
FROM DATAEXPERT_STUDENT.raw_pos.truck t
JOIN DATAEXPERT_STUDENT.raw_pos.franchise f
    ON t.franchise_id = f.franchise_id;

SELECT 
    FRANCHISEE_FIRST_NAME, 
    FRANCHISEE_LAST_NAME, 
    TRUCK_ID, 
    MAKE 
FROM DATAEXPERT_STUDENT.HARMONIZED.TRUCK_FRANCHISE_V
WHERE FRANCHISEE_FIRST_NAME = 'Sara'

DESCRIBE VIEW DATAEXPERT_STUDENT.HARMONIZED.TRUCK_FRANCHISE_V;

DROP VIEW DATAEXPERT_STUDENT.HARMONIZED.TRUCK_FRANCHISE;

CREATE OR REPLACE MATERIALIZED VIEW DATAEXPERT_STUDENT.HARMONIZED.TRUCK_FRANCHISE_V AS
SELECT
    t.*,
    f.first_name AS franchisee_first_name,
    f.last_name AS franchisee_last_name
FROM DATAEXPERT_STUDENT.raw_pos.truck t
JOIN DATAEXPERT_STUDENT.raw_pos.franchise f
    ON t.franchise_id = f.franchise_id;

CREATE OR REPLACE VIEW DATAEXPERT_STUDENT.HARMONIZED.nissan AS
SELECT 
    FRANCHISEE_FIRST_NAME, 
    FRANCHISEE_LAST_NAME, 
    TRUCK_ID, 
    MAKE 
FROM DATAEXPERT_STUDENT.HARMONIZED.TRUCK_FRANCHISE_V
WHERE MAKE = 'Nissan'

DROP VIEW DATAEXPERT_STUDENT.HARMONIZED.nissan;
